In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons

In [36]:
data = make_moons()
print(data)
X = data[0]
Y = data[1]

(array([[ 5.09442530e-02,  1.84891782e-01],
       [-8.38088105e-01,  5.45534901e-01],
       [ 3.45365054e-01,  9.38468422e-01],
       [-4.04783343e-01,  9.14412623e-01],
       [ 2.00000000e+00,  5.00000000e-01],
       [ 7.30832427e-02,  1.24732995e-01],
       [ 6.54634946e-01, -4.38468422e-01],
       [-7.18349350e-01,  6.95682551e-01],
       [ 1.40478334e+00, -4.14412623e-01],
       [-9.60230259e-02,  9.95379113e-01],
       [ 1.96729486e+00,  2.46345416e-01],
       [-1.59599895e-01,  9.87181783e-01],
       [ 3.76510198e-01, -2.81831482e-01],
       [ 9.67294863e-01,  2.53654584e-01],
       [ 1.99179001e+00,  3.72122838e-01],
       [-4.62538290e-01,  8.86599306e-01],
       [-6.72300890e-01,  7.40277997e-01],
       [ 1.34536505e+00, -4.38468422e-01],
       [ 1.92691676e+00,  1.24732995e-01],
       [ 1.57211666e+00, -3.20172255e-01],
       [ 4.04783343e-01,  9.14412623e-01],
       [ 8.01413622e-01,  5.98110530e-01],
       [ 1.46253829e+00, -3.86599306e-01],
       [ 7

In [37]:
print(X)

[[ 5.09442530e-02  1.84891782e-01]
 [-8.38088105e-01  5.45534901e-01]
 [ 3.45365054e-01  9.38468422e-01]
 [-4.04783343e-01  9.14412623e-01]
 [ 2.00000000e+00  5.00000000e-01]
 [ 7.30832427e-02  1.24732995e-01]
 [ 6.54634946e-01 -4.38468422e-01]
 [-7.18349350e-01  6.95682551e-01]
 [ 1.40478334e+00 -4.14412623e-01]
 [-9.60230259e-02  9.95379113e-01]
 [ 1.96729486e+00  2.46345416e-01]
 [-1.59599895e-01  9.87181783e-01]
 [ 3.76510198e-01 -2.81831482e-01]
 [ 9.67294863e-01  2.53654584e-01]
 [ 1.99179001e+00  3.72122838e-01]
 [-4.62538290e-01  8.86599306e-01]
 [-6.72300890e-01  7.40277997e-01]
 [ 1.34536505e+00 -4.38468422e-01]
 [ 1.92691676e+00  1.24732995e-01]
 [ 1.57211666e+00 -3.20172255e-01]
 [ 4.04783343e-01  9.14412623e-01]
 [ 8.01413622e-01  5.98110530e-01]
 [ 1.46253829e+00 -3.86599306e-01]
 [ 7.61445958e-01  6.48228395e-01]
 [-2.84527587e-01  9.58667853e-01]
 [-9.67294863e-01  2.53654584e-01]
 [ 7.15472413e-01 -4.58667853e-01]
 [ 1.22252093e+00 -4.74927912e-01]
 [-9.91790014e-01  1

In [38]:
print(Y)

[1 0 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 0 1
 0 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0
 0 0 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1]


In [39]:
Y = Y.reshape(-1,1)
print(Y)

[[1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]


In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [41]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [42]:
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1-y_true)*np.log(1-y_pred))

In [43]:
input_dim = 2
hidden_dim = 4
output_dim = 1
learning_rate = 0.1

def initialise_parameters():
    np.random.seed(42)
    weights_ih = np.random.randn(input_dim, hidden_dim)
    bias_h = np.zeros((1,hidden_dim))
    weights_ho = np.random.randn(hidden_dim, output_dim)
    bias_o = np.zeros((1, output_dim))
    print(weights_ih, bias_h, weights_ho, bias_o)

    return weights_ih, bias_h, weights_ho, bias_o
    

In [44]:
def forward_propagation(X, weights_ih, bias_h, weights_ho, bias_o):
    hidden_input = np.dot(X, weights_ih) + bias_h
    hidden_output = sigmoid(hidden_input)
    output_input = np.dot(hidden_output, weights_ho) + bias_o
    output = sigmoid(output_input)

    return hidden_output, output

In [45]:
def backward_propagation(X, Y, hidden_output, output, weights_ho):
    m = X.shape[0]
    output_error = output - Y
    output_gradient = output_error * sigmoid_derivative(output)

    hidden_error = np.dot(output_gradient, weights_ho.T)
    hidden_gradient = hidden_error * sigmoid_derivative(hidden_output)

    d_weights_ih = np.dot(X.T, hidden_gradient) / m
    d_bias_h = np.sum(hidden_gradient, axis=0, keepdims=True) / m
    d_weights_ho = np.dot(hidden_output.T, output_gradient) / m
    d_bias_o = np.sum(output_gradient, axis = 0, keepdims = True) / m

    return d_weights_ih, d_bias_h, d_weights_ho, d_bias_o

In [46]:
weights_ih, bias_h, weights_ho, bias_o = initialise_parameters()

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]] [[0. 0. 0. 0.]] [[-0.46947439]
 [ 0.54256004]
 [-0.46341769]
 [-0.46572975]] [[0.]]


In [47]:
for epoch in range(100):
    hidden_output, output = forward_propagation(X_train, weights_ih, bias_h, weights_ho, bias_o)
    loss = binary_cross_entropy(Y_train, output)

    d_weights_ih, d_bias_h, d_weights_ho, d_bias_o = backward_propagation(X_train, Y_train, hidden_output, output, weights_ho)
    weights_ih -= d_weights_ih * learning_rate
    bias_h -= d_bias_h * learning_rate
    weights_ho -= d_weights_ho * learning_rate
    bias_o -= d_bias_o * learning_rate

    if epoch%10 == 0:
        print(f"Epoch: {epoch} Loss = {loss:.4f}")

Epoch: 0 Loss = 0.7558
Epoch: 10 Loss = 0.7440
Epoch: 20 Loss = 0.7341
Epoch: 30 Loss = 0.7257
Epoch: 40 Loss = 0.7187
Epoch: 50 Loss = 0.7128
Epoch: 60 Loss = 0.7078
Epoch: 70 Loss = 0.7034
Epoch: 80 Loss = 0.6995
Epoch: 90 Loss = 0.6961


In [48]:
hidden_output, output = forward_propagation(X_test, weights_ih, bias_h, weights_ho, bias_o)
final_loss = binary_cross_entropy(Y_test, output)
print(f"Final Loss = {final_loss:.4f}")

Final Loss = 0.7061
