In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [72]:
df = pd.read_csv('~/Downloads/Lab1/Logistic Regression/BankNote.csv')

In [73]:
df.shape

(1096, 5)

In [74]:
df.head()

VWTI     SWTI     CWTI        EI  Class
0  2.2634  -4.4862   3.6558 -0.612510      0
1  3.2718   1.7837   2.1161  0.613340      0
2 -3.9411 -12.8792  13.0597 -3.312500      1
3  0.5195  -3.2633   3.0895 -0.984900      0
4  2.5698  -4.4076   5.9856  0.078002      0

In [75]:
X_train_count = int(df.shape[0] * 0.8)
print(X_train_count)

876


In [76]:
1096 - 876

220

In [77]:
X_train = df.iloc[:X_train_count,:-1].values
Y_train = df.iloc[:X_train_count,-1].values
print(X_train)
print(Y_train)

[[  2.2634   -4.4862    3.6558   -0.61251]
 [  3.2718    1.7837    2.1161    0.61334]
 [ -3.9411  -12.8792   13.0597   -3.3125 ]
 ...
 [ -1.6514   -8.4985    9.1122    1.2379 ]
 [  3.0333   -2.5928    2.3183    0.303  ]
 [  1.4276    8.3847   -2.0995   -1.9677 ]]
[0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0
 1 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 1
 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 0 0
 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0
 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1
 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0
 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1
 0 1 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1
 1 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 

In [94]:
X_test = df.iloc[X_train_count:,:-1].values
Y_test = df.iloc[X_train_count:,-1].values
print(X_test.shape)
print(Y_test.shape)

(220, 4)
(220,)


In [95]:
df.isnull()

VWTI   SWTI   CWTI     EI  Class
0     False  False  False  False  False
1     False  False  False  False  False
2     False  False  False  False  False
3     False  False  False  False  False
4     False  False  False  False  False
...     ...    ...    ...    ...    ...
1091  False  False  False  False  False
1092  False  False  False  False  False
1093  False  False  False  False  False
1094  False  False  False  False  False
1095  False  False  False  False  False

[1096 rows x 5 columns]

In [96]:
V_score_mean = np.mean(X_train[0])
V_score_median = np.median(X_train[0])
V_score_min = np.min(X_train[0])
V_score_max = np.max(X_train[0])

print("VWTI Mean",V_score_mean)
print("VWTI Median",V_score_median)
print("VWTI Min",V_score_min)
print("VWTI Max",V_score_max)

VWTI Mean 0.20512249999999996
VWTI Median 0.825445
VWTI Min -4.4862
VWTI Max 3.6558


In [97]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [98]:
def fit(X, Y, learning_rate = 0.01, iterations = 1000):
    no_samples, no_features = X.shape
    W = np.zeros(no_features)
    b = 0
    print("W", W, b)
    
    for _ in range(iterations):
#         print("X", X)
#         print("Y", Y)
        W,b = update_weights(X, Y, W, b, learning_rate, no_samples)
    return W, b

In [99]:
def log_pred(X, W, b):
    z = X.dot(W) + b
    return sigmoid(z)

In [100]:
def update_weights(X, Y, W, b, learning_rate, no_samples):
#     print("X shape", X.shape)
#     print("Y shape", Y.shape)
#     print("W shape", W.shape)
    Y_pred = log_pred(X, W, b)
#     print(Y_pred)
    dW = (1/no_samples) * (np.dot(X.T, Y_pred - Y))
    db = (1/no_samples) * (np.sum(Y_pred - Y))
    W -= learning_rate * dW
    b -= learning_rate * db
    return W, b

In [101]:
W, b = fit(X_train, Y_train, 0.01, 1000)
print(W, b)

W [0. 0. 0. 0.] 0
[-1.16064555 -0.63264685 -0.63672208 -0.28370109] 0.5079029056826253


In [102]:
def pred_class(prob):
    return (prob >=0.5).astype(int)

In [103]:
Y_pred_prob = log_pred(X_test, W, b)
print(Y_pred_prob)

[6.61589021e-01 2.26072059e-01 7.80356418e-01 9.75881941e-01
 1.79746337e-02 9.93571973e-03 9.52810204e-01 9.26673672e-01
 9.05518592e-01 2.36410223e-02 1.53192846e-03 1.17658259e-02
 5.13305712e-01 8.99913160e-01 2.04467414e-03 9.49507052e-01
 3.64366333e-03 2.65192645e-03 4.47993800e-01 1.10997676e-02
 5.97190346e-01 9.39526733e-01 9.14351778e-04 2.93370782e-03
 1.70818063e-03 8.26604802e-01 3.19930357e-02 3.16462684e-01
 3.72059299e-03 9.45265402e-02 3.52301862e-03 2.16415266e-03
 1.87957834e-04 9.74387185e-01 9.56386466e-01 9.08864538e-01
 4.97302599e-02 4.40994687e-01 4.85987513e-03 1.03066685e-03
 4.72590435e-03 1.58803456e-03 1.09560155e-03 9.42695387e-04
 9.00008983e-01 1.59215245e-01 7.10544801e-03 9.16593123e-04
 7.27907135e-01 4.43149055e-03 7.87306866e-04 7.94134450e-03
 8.47863660e-01 5.29759400e-03 7.13347076e-03 5.85870931e-03
 3.12011001e-04 7.90044116e-01 9.06652851e-01 9.16878146e-01
 9.09217459e-04 5.50641758e-03 2.26047789e-03 9.81354110e-01
 3.21568260e-03 7.258317

In [104]:
print(pred_class(Y_pred_prob))

[1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 1 1 1 0 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0
 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1
 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]


In [105]:
Y_pred_prob.shape

(220,)

In [106]:
accuracy = np.mean( pred_class(Y_pred_prob) == Y_test)
print(accuracy*100)

97.27272727272728
